app:
  scheduler:
    enabled: false
    interval: PT10S
    force-check-delay: 10s

github-client:
  base-url: ${GITHUB_BASE_URL:"https://api.github.com"}
  per-page: 50

stack-overflow-client:
  base-url: ${STACK_OVERFLOW_BASE_URL:"https://api.stackexchange.com/2.3"}

bot-client:
  base-url: ${BOT_CLIENT_BASE_URL:"https://localhost:8090"}

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${SCRAPPER_DB_DATABASE:scrapper}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/scrapper-db.yaml

server:
  port: ${SCRAPPER_SERVER_PORT:8080}

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
